name: Static analysis

on:
  push:
    branches: [2.x]
  pull_request:
    branches: [2.x]

jobs:
  static:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.5]
        laravel: [13.*]

    name: Static tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-progress --ansi --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --no-progress --ansi --no-security-blocking

      - name: Refacto
        run: composer test:refacto

      - name: Linting
        run: composer test:lint

      - name: Static analysis
        run: composer test:analyse
